/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    RedirectLinkCurto: typeof import('./src/components/RedirectLinkCurto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortenedUrlDialog: typeof import('./src/components/ShortenedUrlDialog.vue')['default']
    ShowUrlShortenedDialog: typeof import('./src/components/ShowUrlShortenedDialog.vue')['default']
    Teste: typeof import('./src/components/Teste.vue')['default']
  }
}
